name: main

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  flakes:
    name: Check Nix flakes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/nix

      - name: Check Nix flake
        run: nix flake check --all-systems --print-build-logs --keep-going

      # - name: Check all existing Nix flakes
      #   run: |
      #     export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1
      #     nix run .#checkFlakes

  slides:
    name: Build workshop slides
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/nix

      - name: Build slides
        run: nix build .#slides

      - name: Upload slides artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: result

  pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - flakes
      - slides
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
